auth    = require '@/local/middleware/auth'
toLower = require 'lodash/toLower'


module.exports = (router) ->

  R = (path, rm, ...mw) ->
    rt = (try (require "@/routes/#{path}")) ? (require '@/routes/hello')
    mw = if rm then mw else [mw..., rt]
    rm = if rm then (toLower rm) else 'post'
    (router[rm] path, mw...)

  # --

  (R '/v2/card/retrieve',                                     null, (auth 'web'))
  (R '/v2/card/update',                                       null, (auth 'web'))
  (R '/v2/game/sheet/:code/game-sheet.pdf',                  'GET', (auth 'none'), (require '@/routes/v2/game/sheet/pdf'))
  (R '/v2/game/sheet/:code/preview',                         'GET', (auth 'none'), (require '@/routes/v2/game/sheet/preview'))
  (R '/v2/game/sheet/retrieve',                               null, (auth 'web'))
  (R '/v2/games/list',                                        null, (auth 'web'))
  (R '/v2/global/divisions/retrieve',                         null, (auth 'maybe'))
  (R '/v2/global/games/list',                                 null, (auth 'maybe'))
  (R '/v2/global/standings/retrieve',                         null, (auth 'maybe'))
  (R '/v2/invite-code/league-free-agent/retrieve',            null, (auth 'web'))
  (R '/v2/invite-code/season-admin/retrieve',                 null, (auth 'web'))
  (R '/v2/invite-code/season-team/retrieve',                  null, (auth 'web'))
  (R '/v2/invite-code/team-manager/retrieve',                 null, (auth 'web'))
  (R '/v2/invite-code/team-player/retrieve',                  null, (auth 'web'))
  (R '/v2/invite/league-free-agent/retrieve',                 null, (auth 'web'))
  (R '/v2/invite/season-admin/accept',                        null, (auth 'web'))
  (R '/v2/invite/season-admin/retrieve',                      null, (auth 'web'))
  (R '/v2/invite/season-team/retrieve',                       null, (auth 'web'))
  (R '/v2/invite/team-manager/retrieve',                      null, (auth 'web'))
  (R '/v2/invite/team-player/retrieve',                       null, (auth 'web'))
  (R '/v2/league/cards/list',                                 null, (auth 'web'))
  (R '/v2/league/retrieve',                                   null, (auth 'web'))
  (R '/v2/league/seasons/list',                               null, (auth 'web'))
  (R '/v2/leagues/list',                                      null, (auth 'web'))
  (R '/v2/payment/retrieve',                                  null, (auth 'web'))
  (R '/v2/payments/list',                                     null, (auth 'web'))
  (R '/v2/registrations/league-free-agent/create',            null, (auth 'web'))
  (R '/v2/registrations/list',                                null, (auth 'web'))
  (R '/v2/registrations/season-team/cancel',                  null, (auth 'web'))
  (R '/v2/registrations/season-team/create',                  null, (auth 'web'))
  (R '/v2/registrations/team-manager/create',                 null, (auth 'web'))
  (R '/v2/registrations/team-player/create',                  null, (auth 'web'))
  (R '/v2/season-settings/player-registration-status/update', null, (auth 'web'))
  (R '/v2/season-settings/prices/update',                     null, (auth 'web'))
  (R '/v2/season-settings/required-info/update',              null, (auth 'web'))
  (R '/v2/season-settings/retrieve',                          null, (auth 'web'))
  (R '/v2/season-settings/roster-player-limit/update',        null, (auth 'web'))
  (R '/v2/season-settings/team-manager-limit/update',         null, (auth 'web'))
  (R '/v2/season-settings/team-player-limit/update',          null, (auth 'web'))
  (R '/v2/season-settings/team-registration-status/update',   null, (auth 'web'))
  (R '/v2/season/divisions/list',                             null, (auth 'web'))
  (R '/v2/season/game/cancel',                                null, (auth 'web'))
  (R '/v2/season/game/delete',                                null, (auth 'web'))
  (R '/v2/season/game/retrieve',                              null, (auth 'web'))
  (R '/v2/season/game/sheet/retrieve',                        null, (auth 'web'))
  (R '/v2/season/game/update',                                null, (auth 'web'))
  (R '/v2/season/games/create',                               null, (auth 'web'))
  (R '/v2/season/games/list',                                 null, (auth 'web'))
  (R '/v2/season/misconduct/retrieve',                        null, (auth 'web'))
  (R '/v2/season/misconduct/update',                          null, (auth 'web'))
  (R '/v2/season/misconducts/create',                         null, (auth 'web'))
  (R '/v2/season/misconducts/list',                           null, (auth 'web'))
  (R '/v2/season/payments/create',                            null, (auth 'web'))
  (R '/v2/season/payments/list',                              null, (auth 'web'))
  (R '/v2/season/people/list',                                null, (auth 'web'))
  (R '/v2/season/registrations/list',                         null, (auth 'web'))
  (R '/v2/season/retrieve',                                   null, (auth 'web'))
  (R '/v2/season/standings/list',                             null, (auth 'web'))
  (R '/v2/season/team/division/update',                       null, (auth 'web'))
  (R '/v2/season/team/games/list',                            null, (auth 'web'))
  (R '/v2/season/team/people/list',                           null, (auth 'web'))
  (R '/v2/season/team/player/retrieve',                       null, (auth 'web'))
  (R '/v2/season/team/remove-player',                         null, (auth 'web'))
  (R '/v2/season/team/retrieve',                              null, (auth 'web'))
  (R '/v2/season/teams/list',                                 null, (auth 'web'))
  (R '/v2/seasons/create',                                    null, (auth 'web'))
  (R '/v2/team/remove-player',                                null, (auth 'web'))
  (R '/v2/team/retrieve',                                     null, (auth 'web'))
  (R '/v2/teams/list',                                        null, (auth 'web'))
  (R '/v2/user/full-name/update',                             null, (auth 'web'))



  # --

  R('/v1/hello-world',                                                null, auth('none'))

  R('/v1/-/schedule/retrieve',                                        null, auth('none'))
  # R('/v1/-/standings/retrieve',                                       null, auth('none'))
  R('/v1/games/retrieve',                                             null, auth('web'))
  R('/v1/leagues/seasons/games/cancel',                               null, auth('web'))
  R('/v1/leagues/seasons/games/create',                               null, auth('web'))
  R('/v1/leagues/seasons/games/delete',                               null, auth('web'))
  R('/v1/leagues/seasons/games/list',                                 null, auth('web'))
  R('/v1/leagues/seasons/facilities/list',                            null, auth('web'))
  R('/v1/leagues/seasons/spaces/list',                                null, auth('web'))
  # R('/v1/leagues/seasons/misconducts/create',                         null, auth('web'))
  # R('/v1/leagues/seasons/misconducts/end',                            null, auth('web'))
  # R('/v1/leagues/seasons/misconducts/list',                           null, auth('web'))
  # R('/v1/leagues/seasons/misconducts/people/list',                    null, auth('web'))
  R('/v1/leagues/seasons/notifications/accept-remove-player-request', null, auth('web'))
  R('/v1/leagues/seasons/notifications/list',                         null, auth('web'))
  R('/v1/leagues/seasons/notifications/reject-remove-player-request', null, auth('web'))
  # R('/v1/leagues/seasons/payments/create',                            null, auth('web'))
  R('/v1/leagues/seasons/payments/list',                              null, auth('web'))
  R('/v1/leagues/seasons/people/list',                                null, auth('web'))
  # R('/v1/leagues/seasons/standings/list',                             null, auth('web'))
  R('/v1/leagues/seasons/teams/request-to-remove-player',             null, auth('web'))
  R('/v1/people/list',                                                null, auth('web'))
  R('/v1/user/address/update',                                        null, auth('web'))
  R('/v1/user/birthday/update',                                       null, auth('web'))
  R('/v1/user/display-name/update',                                   null, auth('web'))
  # R('/v1/user/full-name/update',                                      null, auth('web'))
  R('/v1/user/gender/update',                                         null, auth('web'))
  R('/v1/user/retrieve',                                              null, auth('web'))



  R('/v1/auth/fb-token',                                     'GET',  auth('none'), require('@/routes/auth/fb-token'))
  R('/v1/auth/send-code-link',                               'POST', auth('none'), require('@/routes/auth/send-code-link'))
  R('/v1/game-sheets/:id',                                   'GET',  auth('none'), require('@/routes/game-sheets/retrieve'))
  # R('/v1/game-sheets/:id/game-sheet.pdf',                    'GET',  auth('none'), require('@/routes/game-sheets/retrieve-pdf'))
  R('/v1/games',                                             'GET',  auth('web'),  require('@/routes/games/list'))
  R('/v1/hello',                                             'GET',  auth('none'), require('@/routes/hello'))
  R('/v2/hello',                                             'GET',  auth('none'), require('@/routes/hello'))
  # R('/v1/invite-links/league-free-agent/:id',                'GET',  auth('web'),  require('@/routes/invite-links/league-free-agent/retrieve'))
  # R('/v1/invite-links/league-season-team-manager/:id',       'GET',  auth('web'),  require('@/routes/invite-links/league-season-team-manager/retrieve'))
  # R('/v1/invite-links/league-season-team-player/:id',        'GET',  auth('web'),  require('@/routes/invite-links/league-season-team-player/retrieve'))
  # R('/v1/invite-links/league-season-team/:id',               'GET',  auth('web'),  require('@/routes/invite-links/league-season-team/retrieve'))
  # R('/v1/league/free-agent-cards',                           'GET',  auth('web'),  require('@/routes/l-free-agent-cards/list'))
  R('/v1/league/season/divisions',                           'GET',  auth('web'),  require('@/routes/ls-divisions/list'))
  R('/v1/league/season/games/:id/date-time',                 'POST', auth('web'),  require('@/routes/ls-games/update-date-time'))
  R('/v1/league/season/games/:id/location',                  'POST', auth('web'),  require('@/routes/ls-games/update-location'))
  R('/v1/league/season/games/:id/results',                   'POST', auth('web'),  require('@/routes/ls-games/update-results'))
  R('/v1/league/season/payments',                            'GET',  auth('web'),  require('@/routes/ls-payments/list'))
  R('/v1/league/season/people',                              'GET',  auth('web'),  require('@/routes/ls-people/list'))
  R('/v1/league/season/registrations',                       'GET',  auth('web'),  require('@/routes/ls-registrations/list'))
  R('/v1/league/season/settings/player-registration-status', 'POST', auth('web'),  require('@/routes/ls-settings/update-player-registration-status'))
  R('/v1/league/season/settings/team-manager-limit',         'POST', auth('web'),  require('@/routes/ls-settings/update-team-manager-limit'))
  R('/v1/league/season/settings/team-player-limit',          'POST', auth('web'),  require('@/routes/ls-settings/update-team-player-limit'))
  R('/v1/league/season/settings/team-registration-status',   'POST', auth('web'),  require('@/routes/ls-settings/update-team-registration-status'))
  # R('/v1/league/season/teams',                               'GET',  auth('web'),  require('@/routes/ls-teams/list'))
  R('/v1/leagues',                                           'GET',  auth('web'),  require('@/routes/leagues/list'))
  R('/v1/leagues/:id',                                       'GET',  auth('web'),  require('@/routes/leagues/retrieve'))
  # R('/v1/leagues/:id/create-season',                         'POST', auth('web'),  require('@/routes/leagues/create-season'))
  # R('/v1/payments',                                          'POST', auth('web'),  require('@/routes/payments/create'))
  R('/v1/payments/find',                                     'GET',  auth('web'),  require('@/routes/payments/find'))
  # R('/v1/player-cards',                                      'GET',  auth('web'),  require('@/routes/player-cards/list'))
  R('/v1/registration-settings/league-season-team/:id',      'GET',  auth('web'),  require('@/routes/registration-settings/league-season-team/retrieve'))
  R('/v1/registrations',                                     'GET',  auth('web'),  require('@/routes/registrations/list'))
  R('/v1/registrations/league-free-agent',                   'POST', auth('web'),  require('@/routes/registrations/league-free-agent/create'))
  R('/v1/registrations/league-season-team',                  'GET',  auth('web'),  require('@/routes/registrations/league-season-team/list'))
  R('/v1/registrations/league-season-team',                  'POST', auth('web'),  require('@/routes/registrations/league-season-team/create'))
  R('/v1/registrations/league-season-team-manager',          'POST', auth('web'),  require('@/routes/registrations/league-season-team-manager/create'))
  R('/v1/registrations/league-season-team-player',           'POST', auth('web'),  require('@/routes/registrations/league-season-team-player/create'))
  R('/v1/seasons',                                           'GET',  auth('web'),  require('@/routes/seasons/list'))
  R('/v1/seasons/:id',                                       'GET',  auth('web'),  require('@/routes/seasons/retrieve'))
  R('/v1/sites/games',                                       'GET',  auth('none'), require('@/routes/sites-games/list'))
  R('/v1/teams',                                             'GET',  auth('web'),  require('@/routes/teams/list'))
  R('/v1/teams/:id',                                         'GET',  auth('web'),  require('@/routes/teams/retrieve'))
  R('/v1/teams/remove-player',                               'POST', auth('web'),  require('@/routes/teams/remove-player'))
  R('/v1/webhooks/stripe/checkout-session-completed',        'POST', auth('none'), require('@/routes/webhooks/stripe/checkout-session-completed'))



  # R('/v1/divisions',                                    'GET',  auth('web'),  require('@/routes/ls-divisions/list'))

  # Archive
  # R('/v1/registrations/league-season-player',                'GET',  auth('web'),  require('@/routes/registrations/league-season-player/list'))
  # R('/v1/registrations/league-season-player',                'POST', auth('web'),  require('@/routes/registrations/league-season-player/create'))
  # R('/v1/auth/send-add-email-code',                     'POST', auth('web'),  require('@/routes/auth/send-add-email-code'))
  # R('/v1/auth/send-add-email-message',                  'POST', auth('web'),  require('@/routes/auth/send-add-email-message'))
  # R('/v1/auth/send-add-phone-code',                     'POST', auth('web'),  require('@/routes/auth/send-add-phone-code'))
  # R('/v1/auth/send-code',                               'POST', auth('none'), require('@/routes/auth/send-code'))
  # R('/v1/auth/send-sign-in-email',                      'POST', auth('none'), require('@/routes/auth/send-sign-in-email'))
  # R('/v1/user',                                         'POST', auth('web'),  require('@/routes/user/create'))
  # R('/v1/user/add-email',                               'POST', auth('web'),  require('@/routes/user/add-email'))
  # R('/v1/user/add-phone',                               'POST', auth('web'),  require('@/routes/user/add-phone'))
